"""Flows: joins, rates, and a compiled JAX vector field."""

from summer4.flows.actualize import (
    EntryEdges,
    ExitEdges,
    FlowEdges,
    TransitionEdges,
    actualize,
)
from summer4.flows.compiled import (
    CompiledModel,
    FlowModel,
    GroupedRate,
    SaveContext,
    euler,
    eval_closed,
    numpy_euler,
)
from summer4.flows.edges import EdgeMap, EdgeRoles
from summer4.flows.initial import REMAINDER, InitialPopulation, Split
from summer4.flows.join import (
    TraitChain,
    TraitMatrix,
    identity_join,
    selector_properties,
    selector_values,
)
from summer4.flows.rates import (
    BinOp,
    Const,
    FieldRef,
    FlowRef,
    GaussianPulse,
    Interp,
    Multiply,
    Overwrite,
    Param,
    Reduce,
    Time,
    Transform,
    UnaryOp,
    as_adjust,
    as_rate,
    clip,
    derived_refs,
    exp,
    floor,
    log,
    maximum,
    minimum,
    sqrt,
    tanh,
)
from summer4.flows.stages import Prepared
from summer4.flows.types import EntryFlow, ExitFlow, TransitionFlow

__all__ = [
    "BinOp",
    "CompiledModel",
    "Const",
    "EdgeMap",
    "EdgeRoles",
    "EntryEdges",
    "EntryFlow",
    "ExitEdges",
    "ExitFlow",
    "FieldRef",
    "FlowEdges",
    "FlowModel",
    "FlowRef",
    "GaussianPulse",
    "GroupedRate",
    "InitialPopulation",
    "Interp",
    "Multiply",
    "Overwrite",
    "Param",
    "Prepared",
    "REMAINDER",
    "Reduce",
    "SaveContext",
    "Split",
    "Time",
    "TraitChain",
    "TraitMatrix",
    "Transform",
    "TransitionEdges",
    "TransitionFlow",
    "UnaryOp",
    "actualize",
    "as_adjust",
    "as_rate",
    "clip",
    "derived_refs",
    "euler",
    "eval_closed",
    "exp",
    "floor",
    "identity_join",
    "log",
    "maximum",
    "minimum",
    "numpy_euler",
    "selector_properties",
    "selector_values",
    "sqrt",
    "tanh",
]
